# Builds when a release is published.
name: Build Workflow

permissions: write-all

on:
  release:
    types:
      - published

jobs:
  run:
    name: Build Release Package
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@master
      with:
        version: "1.11.x"
        no-spcomp-proxy: true

    - name: Setup Ninja Build
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.0

    - name: Build Files
      run: |
        python3 configure.py
        ninja
        
    - name: Release
      uses: softprops/action-gh-release@master
      with:
        files: |
          ./build/plugins/sf2_hint_on_look_public.smx
          ./build/translations/sf2_hint.phrases.txt